 #  _____               _                  ____   _                    _   
 # | ____|  _ __     __| |   ___   _ __   / ___| | |__     ___   ___  | |_ 
 # |  _|   | '_ \   / _` |  / _ \ | '__| | |     | '_ \   / _ \ / __| | __|
 # | |___  | | | | | (_| | |  __/ | |    | |___  | | | | |  __/ \__ \ | |_ 
 # |_____| |_| |_|  \__,_|  \___| |_|     \____| |_| |_|  \___| |___/  \__|
 #          by fernanACM
 
 # Portable EnderChest for PocketMine-MP 4.0 Servers.
 # Everything can be configured via 'config.yml', the name of the 
 # enderchest, a custom sound function can also be added. The sounds 
 # page of the game: https://www.digminecraft.com/lists/sound_list_pe.php

# ======(SETTINGS)======
Settings:
  EnderChest-name: "EnderChest inventory"
  EnderChest-no-sound: true
  EnderChest-sound: "random.enderchestopen"
