---
1:
  spawn: '{"x":256.2896,"y":66,"z":281.2617,"world":"cafeteria"}'
  props: '{"name":"Boss","skin":"ID01","hp":"20","speed":"0.6","damage":"1","scale":"1","attack_range":"2","attack_interval":"16","respawn_cooldown":"0"}'
  reward:
    items: []
    commands: []
    money: 100
...
